name: xscale-doc
dependencies:
  - python=2.7
  - ipython
  - numpy
  - scipy
  - xarray
  - pandas
  - dask
  - numba
  - matplotlib
  - seaborn
  - graphviz
  - sphinx
  - sphinx_rtd_theme
  - numpydoc